In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
tf.__version__

'2.1.0'

In [5]:
data = pd.read_csv("graduate-admissions/Admission_Predict_Ver1.1.csv")
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [8]:
continuous_features = data[["GRE Score", "TOEFL Score", "University Rating",
                            "SOP", "LOR ", "CGPA"]].values / 100

In [9]:
continuous_features

array([[3.37  , 1.18  , 0.04  , 0.045 , 0.045 , 0.0965],
       [3.24  , 1.07  , 0.04  , 0.04  , 0.045 , 0.0887],
       [3.16  , 1.04  , 0.03  , 0.03  , 0.035 , 0.08  ],
       ...,
       [3.3   , 1.2   , 0.05  , 0.045 , 0.05  , 0.0956],
       [3.12  , 1.03  , 0.04  , 0.04  , 0.05  , 0.0843],
       [3.27  , 1.13  , 0.04  , 0.045 , 0.045 , 0.0904]])

In [10]:
categorical_research_features = data[["Research"]].values

In [11]:
categorical_research_features

array([[1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
    

In [14]:
x = np.concatenate([continuous_features, categorical_research_features], axis = 1)
x

array([[3.37  , 1.18  , 0.04  , ..., 0.045 , 0.0965, 1.    ],
       [3.24  , 1.07  , 0.04  , ..., 0.045 , 0.0887, 1.    ],
       [3.16  , 1.04  , 0.03  , ..., 0.035 , 0.08  , 1.    ],
       ...,
       [3.3   , 1.2   , 0.05  , ..., 0.05  , 0.0956, 1.    ],
       [3.12  , 1.03  , 0.04  , ..., 0.05  , 0.0843, 0.    ],
       [3.27  , 1.13  , 0.04  , ..., 0.045 , 0.0904, 0.    ]])

In [17]:
y = data[["Chance of Admit "]].values
y

array([[0.92],
       [0.76],
       [0.72],
       [0.8 ],
       [0.65],
       [0.9 ],
       [0.75],
       [0.68],
       [0.5 ],
       [0.45],
       [0.52],
       [0.84],
       [0.78],
       [0.62],
       [0.61],
       [0.54],
       [0.66],
       [0.65],
       [0.63],
       [0.62],
       [0.64],
       [0.7 ],
       [0.94],
       [0.95],
       [0.97],
       [0.94],
       [0.76],
       [0.44],
       [0.46],
       [0.54],
       [0.65],
       [0.74],
       [0.91],
       [0.9 ],
       [0.94],
       [0.88],
       [0.64],
       [0.58],
       [0.52],
       [0.48],
       [0.46],
       [0.49],
       [0.53],
       [0.87],
       [0.91],
       [0.88],
       [0.86],
       [0.89],
       [0.82],
       [0.78],
       [0.76],
       [0.56],
       [0.78],
       [0.72],
       [0.7 ],
       [0.64],
       [0.64],
       [0.46],
       [0.36],
       [0.42],
       [0.48],
       [0.47],
       [0.54],
       [0.56],
       [0.52],
       [0.55],
       [0.

In [18]:
train_features, test_features, train_labels, test_labels = train_test_split(x, y, test_size = 0.2)

In [24]:
train_features.shape, test_features.shape, train_labels.shape, test_labels.shape

((400, 7), (100, 7), (400, 1), (100, 1))

In [25]:
x = tf.constant(train_features, dtype = tf.float32)
y = tf.constant(train_labels, dtype = tf.float32)

In [28]:
x.shape, y.shape

(TensorShape([400, 7]), TensorShape([400, 1]))

In [32]:
x_test = tf.constant(test_features, dtype = tf.float32)
y_test = tf.constant(test_labels, dtype = tf.float32)

In [35]:
x_test.shape, y_test.shape

(TensorShape([100, 7]), TensorShape([100, 1]))

In [36]:
def mean_square_error(x, y_pred):
    return tf.reduce_mean(tf.square(y_pred - y))

In [37]:
def mean_square_error_deriv(y, y_pred):
    return tf.reshape(tf.reduce_mean(2 * (y_pred - y)), [1, 1])

In [38]:
def h(x, weights, bias):
    return tf.tensordot(x, weights, axes = 1) + bias

In [40]:
num_epochs = 10
num_samples = x.shape[0]
batch_size = 10
learning_rate = 0.001

In [42]:
dataset = tf.data.Dataset.from_tensor_slices((x, y))
dataset = dataset.shuffle(500).repeat(num_epochs).batch(batch_size)
iterator = dataset.__iter__()

In [43]:
iterator